[package]
name = "pixelpwnr"
version = "0.1.0"
authors = ["Tim Vis√©e <timvisee@gmail.com>"]

[dependencies]
bufstream = "0.1"
clap = "2.30"
image = "0.18"
num_cpus = "1.8"
regex = "0.2"

[profile.release]
lto = true
